# Generated by Django 3.2.9 on 2021-11-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='название')),
                ('price', models.CharField(max_length=225, verbose_name='цена')),
                ('Per_Month', models.CharField(max_length=225, verbose_name='в месяц')),
                ('description', models.CharField(max_length=120, verbose_name='описание')),
            ],
        ),
    ]
