# Generated by Django 3.2.9 on 2021-11-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамиля')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='logo')),
                ('zvaniya', models.CharField(max_length=225, verbose_name='звание')),
                ('description', models.CharField(max_length=225, verbose_name='Описание')),
                ('age', models.CharField(max_length=32, verbose_name='возраст')),
                ('Department', models.CharField(max_length=225, verbose_name='оделение')),
                ('Experience', models.CharField(max_length=225, verbose_name='опыт')),
                ('Phone', models.CharField(max_length=22, verbose_name='телефон')),
                ('email', models.CharField(max_length=225, verbose_name='email')),
                ('address', models.CharField(max_length=225, verbose_name='Address')),
                ('Facebook', models.CharField(max_length=225, verbose_name='Facebook')),
                ('Telegram', models.CharField(max_length=225, verbose_name='Telegram')),
                ('Twitter', models.CharField(max_length=225, verbose_name='Twitter')),
                ('Instagram', models.CharField(max_length=225, verbose_name='Instagram')),
            ],
        ),
    ]
