# Generated by Django 3.2.9 on 2021-11-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio', verbose_name='Картинки')),
                ('link_portfolio', models.CharField(max_length=220, verbose_name='Ссылка на партфолио')),
            ],
        ),
    ]
